name: Bug Report
description: Report a Bug or Problem
title: "[Bug]: "
labels: ["bug", "needs review"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report your Issue!
        *Tip: you can use `msrc -i` to generate an issue report link that autofills your System Info for you!*
  - type: input
    id: msrcver
    attributes:
      label: MSRC Version
      description: What MSRC Version Are You Running?
      placeholder: 24.12.28
    validations:
      required: true
  - type: input
    id: md5
    attributes:
      label: MSRC MD5
      description: "What is your MSRC md5? (check with `msrc md5check --only`)"
      placeholder: df19d6afaaaa10093d6507558e93ab1a
    validations:
      required: true
  - type: input
    id: shell
    attributes:
      label: Shell Name & Version
      description: What Shell Are You Running?
      placeholder: bash 5.0.17(1)-release
    validations:
      required: true
  - type: input
    id: system
    attributes:
      label: System Architecture
      description: What type of system are you running on?
      placeholder: "Linux 5.13.0-48-generic x86_64 (Try: uname -spr)"
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: What Operating System/Environment is it?
      placeholder: Linux Mint 20.3 (Una), Arch Linux, Android 9 + Termux 0.118.0 (F_DROID), etc
    validations:
      required: true
  - type: input
    id: libc
    attributes:
      label: C Library
      description: |
        What C Library is your Shell Using?
        Different C Libraries can alter BASH's behavior!
      placeholder: "GNU Libc, Musl Libc, etc. Try: echo ${BASH_VERSINFO[5]}"
    validations:
      required: true
  - type: textarea
    id: shopts
    attributes:
      label: Shell Options
      description: |
        Enter a list of your shell options
      placeholder: |
        autocd
        checkwinsize
        etc...
  - type: textarea
    id: what-happened
    attributes:
      label: What went wrong?
      description: |
        Describe the nature of your issue in detail.
        What were you doing when it happened?
        How often and when does it occur?
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: What SHOULD have happened?
      description: What do you believe should have happened?
  - type: checkboxes
    id: md5prompt
    attributes:
      label: My copy of MSRC is unmodified
      options:
        - label: "I've verified that the md5 matches via `msrc md5check`"
          id: verifiedmd5
          required: true
  - type: checkboxes
    id:  boxes
    attributes:
      label: Be sure to check all that apply
      description: If any of thse apply to your situation, please check them!
      options:
        - label: I have searched through the Open Issues and I'm pretty sure mine isn't a duplicate
          required: true
        - label: My version of MSRC and Enabled Default Extras are up to date with the Master Branch
          required: true
        - label: My Issue is related to one of MSRC's Default Extra Configs (and I've specified which one above)
        - label: My issue actually affects multiple different platforms!
        - label: My issue is severe (Data Loss, etc.)
